// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.1
// - protoc             v3.21.7
// source: api/user/v1/user.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUserAmountTo = "/api.user.v1.User/AmountTo"
const OperationUserAmountToCard = "/api.user.v1.User/AmountToCard"
const OperationUserChangePin = "/api.user.v1.User/ChangePin"
const OperationUserCheckCard = "/api.user.v1.User/CheckCard"
const OperationUserCodeList = "/api.user.v1.User/CodeList"
const OperationUserCreateNonce = "/api.user.v1.User/CreateNonce"
const OperationUserEthAuthorize = "/api.user.v1.User/EthAuthorize"
const OperationUserGetUser = "/api.user.v1.User/GetUser"
const OperationUserLookCard = "/api.user.v1.User/LookCard"
const OperationUserLookCardNew = "/api.user.v1.User/LookCardNew"
const OperationUserLookCardNewTwo = "/api.user.v1.User/LookCardNewTwo"
const OperationUserOpenCard = "/api.user.v1.User/OpenCard"
const OperationUserOpenCardTwo = "/api.user.v1.User/OpenCardTwo"
const OperationUserOrderList = "/api.user.v1.User/OrderList"
const OperationUserOrderListTwo = "/api.user.v1.User/OrderListTwo"
const OperationUserRecordList = "/api.user.v1.User/RecordList"
const OperationUserRewardList = "/api.user.v1.User/RewardList"
const OperationUserSetVip = "/api.user.v1.User/SetVip"
const OperationUserUserRecommend = "/api.user.v1.User/UserRecommend"
const OperationUserWithdraw = "/api.user.v1.User/Withdraw"

type UserHTTPServer interface {
	// AmountTo 转账
	AmountTo(context.Context, *AmountToRequest) (*AmountToReply, error)
	// AmountToCard 划转
	AmountToCard(context.Context, *AmountToCardRequest) (*AmountToCardReply, error)
	ChangePin(context.Context, *ChangePinRequest) (*ChangePinReply, error)
	CheckCard(context.Context, *CheckCardRequest) (*CheckCardReply, error)
	// CodeList 明细列表
	CodeList(context.Context, *CodeListRequest) (*CodeListReply, error)
	CreateNonce(context.Context, *CreateNonceRequest) (*CreateNonceReply, error)
	EthAuthorize(context.Context, *EthAuthorizeRequest) (*EthAuthorizeReply, error)
	// GetUser 个人信息
	GetUser(context.Context, *GetUserRequest) (*GetUserReply, error)
	// LookCard 开卡
	LookCard(context.Context, *LookCardRequest) (*LookCardReply, error)
	// LookCardNew 冻结卡
	LookCardNew(context.Context, *LookCardRequest) (*LookCardReply, error)
	// LookCardNewTwo 补卡
	LookCardNewTwo(context.Context, *LookCardRequest) (*LookCardReply, error)
	// OpenCard 开卡
	OpenCard(context.Context, *OpenCardRequest) (*OpenCardReply, error)
	OpenCardTwo(context.Context, *OpenCardRequest) (*OpenCardReply, error)
	// OrderList 账单列表
	OrderList(context.Context, *OrderListRequest) (*OrderListReply, error)
	OrderListTwo(context.Context, *OrderListTwoRequest) (*OrderListTwoReply, error)
	// RecordList 明细列表
	RecordList(context.Context, *RecordListRequest) (*RecordListReply, error)
	// RewardList 明细列表
	RewardList(context.Context, *RewardListRequest) (*RewardListReply, error)
	// SetVip 设置级别给下级
	SetVip(context.Context, *SetVipRequest) (*SetVipReply, error)
	// UserRecommend 团队信息
	UserRecommend(context.Context, *RecommendListRequest) (*RecommendListReply, error)
	// Withdraw 提现
	Withdraw(context.Context, *WithdrawRequest) (*WithdrawReply, error)
}

func RegisterUserHTTPServer(s *http.Server, srv UserHTTPServer) {
	r := s.Route("/")
	r.POST("/api/app_server/create_nonce", _User_CreateNonce0_HTTP_Handler(srv))
	r.POST("/api/app_server/eth_authorize", _User_EthAuthorize0_HTTP_Handler(srv))
	r.GET("/api/app_server/user", _User_GetUser0_HTTP_Handler(srv))
	r.GET("/api/app_server/recommend_list", _User_UserRecommend0_HTTP_Handler(srv))
	r.GET("/api/app_server/order_list", _User_OrderList0_HTTP_Handler(srv))
	r.GET("/api/app_server/order_list_new", _User_OrderListTwo0_HTTP_Handler(srv))
	r.GET("/api/app_server/reward_list", _User_RewardList0_HTTP_Handler(srv))
	r.GET("/api/app_server/record_list", _User_RecordList0_HTTP_Handler(srv))
	r.GET("/api/app_server/code_list", _User_CodeList0_HTTP_Handler(srv))
	r.POST("/api/app_server/open_card", _User_OpenCard0_HTTP_Handler(srv))
	r.POST("/api/app_server/check_card", _User_CheckCard0_HTTP_Handler(srv))
	r.POST("/api/app_server/open_card_two", _User_OpenCardTwo0_HTTP_Handler(srv))
	r.POST("/api/app_server/look_card", _User_LookCard0_HTTP_Handler(srv))
	r.POST("/api/app_server/look_card_new", _User_LookCardNew0_HTTP_Handler(srv))
	r.POST("/api/app_server/change_card", _User_LookCardNewTwo0_HTTP_Handler(srv))
	r.POST("/api/app_server/change_pin", _User_ChangePin0_HTTP_Handler(srv))
	r.POST("/api/app_server/amount_to_card", _User_AmountToCard0_HTTP_Handler(srv))
	r.POST("/api/app_server/set_vip", _User_SetVip0_HTTP_Handler(srv))
	r.POST("/api/app_server/amount_to", _User_AmountTo0_HTTP_Handler(srv))
	r.POST("/api/app_server/withdraw", _User_Withdraw0_HTTP_Handler(srv))
}

func _User_CreateNonce0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateNonceRequest
		if err := ctx.Bind(&in.SendBody); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserCreateNonce)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateNonce(ctx, req.(*CreateNonceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateNonceReply)
		return ctx.Result(200, reply)
	}
}

func _User_EthAuthorize0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EthAuthorizeRequest
		if err := ctx.Bind(&in.SendBody); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserEthAuthorize)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EthAuthorize(ctx, req.(*EthAuthorizeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EthAuthorizeReply)
		return ctx.Result(200, reply)
	}
}

func _User_GetUser0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserGetUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUser(ctx, req.(*GetUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserReply)
		return ctx.Result(200, reply)
	}
}

func _User_UserRecommend0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RecommendListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserUserRecommend)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UserRecommend(ctx, req.(*RecommendListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RecommendListReply)
		return ctx.Result(200, reply)
	}
}

func _User_OrderList0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in OrderListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserOrderList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.OrderList(ctx, req.(*OrderListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OrderListReply)
		return ctx.Result(200, reply)
	}
}

func _User_OrderListTwo0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in OrderListTwoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserOrderListTwo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.OrderListTwo(ctx, req.(*OrderListTwoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OrderListTwoReply)
		return ctx.Result(200, reply)
	}
}

func _User_RewardList0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RewardListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserRewardList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RewardList(ctx, req.(*RewardListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RewardListReply)
		return ctx.Result(200, reply)
	}
}

func _User_RecordList0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RecordListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserRecordList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RecordList(ctx, req.(*RecordListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RecordListReply)
		return ctx.Result(200, reply)
	}
}

func _User_CodeList0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CodeListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserCodeList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CodeList(ctx, req.(*CodeListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CodeListReply)
		return ctx.Result(200, reply)
	}
}

func _User_OpenCard0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in OpenCardRequest
		if err := ctx.Bind(&in.SendBody); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserOpenCard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.OpenCard(ctx, req.(*OpenCardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OpenCardReply)
		return ctx.Result(200, reply)
	}
}

func _User_CheckCard0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckCardRequest
		if err := ctx.Bind(&in.SendBody); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserCheckCard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckCard(ctx, req.(*CheckCardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckCardReply)
		return ctx.Result(200, reply)
	}
}

func _User_OpenCardTwo0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in OpenCardRequest
		if err := ctx.Bind(&in.SendBody); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserOpenCardTwo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.OpenCardTwo(ctx, req.(*OpenCardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OpenCardReply)
		return ctx.Result(200, reply)
	}
}

func _User_LookCard0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LookCardRequest
		if err := ctx.Bind(&in.SendBody); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserLookCard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LookCard(ctx, req.(*LookCardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LookCardReply)
		return ctx.Result(200, reply)
	}
}

func _User_LookCardNew0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LookCardRequest
		if err := ctx.Bind(&in.SendBody); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserLookCardNew)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LookCardNew(ctx, req.(*LookCardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LookCardReply)
		return ctx.Result(200, reply)
	}
}

func _User_LookCardNewTwo0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LookCardRequest
		if err := ctx.Bind(&in.SendBody); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserLookCardNewTwo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LookCardNewTwo(ctx, req.(*LookCardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LookCardReply)
		return ctx.Result(200, reply)
	}
}

func _User_ChangePin0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChangePinRequest
		if err := ctx.Bind(&in.SendBody); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserChangePin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ChangePin(ctx, req.(*ChangePinRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChangePinReply)
		return ctx.Result(200, reply)
	}
}

func _User_AmountToCard0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AmountToCardRequest
		if err := ctx.Bind(&in.SendBody); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserAmountToCard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AmountToCard(ctx, req.(*AmountToCardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AmountToCardReply)
		return ctx.Result(200, reply)
	}
}

func _User_SetVip0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetVipRequest
		if err := ctx.Bind(&in.SendBody); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserSetVip)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetVip(ctx, req.(*SetVipRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetVipReply)
		return ctx.Result(200, reply)
	}
}

func _User_AmountTo0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AmountToRequest
		if err := ctx.Bind(&in.SendBody); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserAmountTo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AmountTo(ctx, req.(*AmountToRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AmountToReply)
		return ctx.Result(200, reply)
	}
}

func _User_Withdraw0_HTTP_Handler(srv UserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in WithdrawRequest
		if err := ctx.Bind(&in.SendBody); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserWithdraw)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Withdraw(ctx, req.(*WithdrawRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*WithdrawReply)
		return ctx.Result(200, reply)
	}
}

type UserHTTPClient interface {
	AmountTo(ctx context.Context, req *AmountToRequest, opts ...http.CallOption) (rsp *AmountToReply, err error)
	AmountToCard(ctx context.Context, req *AmountToCardRequest, opts ...http.CallOption) (rsp *AmountToCardReply, err error)
	ChangePin(ctx context.Context, req *ChangePinRequest, opts ...http.CallOption) (rsp *ChangePinReply, err error)
	CheckCard(ctx context.Context, req *CheckCardRequest, opts ...http.CallOption) (rsp *CheckCardReply, err error)
	CodeList(ctx context.Context, req *CodeListRequest, opts ...http.CallOption) (rsp *CodeListReply, err error)
	CreateNonce(ctx context.Context, req *CreateNonceRequest, opts ...http.CallOption) (rsp *CreateNonceReply, err error)
	EthAuthorize(ctx context.Context, req *EthAuthorizeRequest, opts ...http.CallOption) (rsp *EthAuthorizeReply, err error)
	GetUser(ctx context.Context, req *GetUserRequest, opts ...http.CallOption) (rsp *GetUserReply, err error)
	LookCard(ctx context.Context, req *LookCardRequest, opts ...http.CallOption) (rsp *LookCardReply, err error)
	LookCardNew(ctx context.Context, req *LookCardRequest, opts ...http.CallOption) (rsp *LookCardReply, err error)
	LookCardNewTwo(ctx context.Context, req *LookCardRequest, opts ...http.CallOption) (rsp *LookCardReply, err error)
	OpenCard(ctx context.Context, req *OpenCardRequest, opts ...http.CallOption) (rsp *OpenCardReply, err error)
	OpenCardTwo(ctx context.Context, req *OpenCardRequest, opts ...http.CallOption) (rsp *OpenCardReply, err error)
	OrderList(ctx context.Context, req *OrderListRequest, opts ...http.CallOption) (rsp *OrderListReply, err error)
	OrderListTwo(ctx context.Context, req *OrderListTwoRequest, opts ...http.CallOption) (rsp *OrderListTwoReply, err error)
	RecordList(ctx context.Context, req *RecordListRequest, opts ...http.CallOption) (rsp *RecordListReply, err error)
	RewardList(ctx context.Context, req *RewardListRequest, opts ...http.CallOption) (rsp *RewardListReply, err error)
	SetVip(ctx context.Context, req *SetVipRequest, opts ...http.CallOption) (rsp *SetVipReply, err error)
	UserRecommend(ctx context.Context, req *RecommendListRequest, opts ...http.CallOption) (rsp *RecommendListReply, err error)
	Withdraw(ctx context.Context, req *WithdrawRequest, opts ...http.CallOption) (rsp *WithdrawReply, err error)
}

type UserHTTPClientImpl struct {
	cc *http.Client
}

func NewUserHTTPClient(client *http.Client) UserHTTPClient {
	return &UserHTTPClientImpl{client}
}

func (c *UserHTTPClientImpl) AmountTo(ctx context.Context, in *AmountToRequest, opts ...http.CallOption) (*AmountToReply, error) {
	var out AmountToReply
	pattern := "/api/app_server/amount_to"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserAmountTo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.SendBody, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) AmountToCard(ctx context.Context, in *AmountToCardRequest, opts ...http.CallOption) (*AmountToCardReply, error) {
	var out AmountToCardReply
	pattern := "/api/app_server/amount_to_card"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserAmountToCard))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.SendBody, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) ChangePin(ctx context.Context, in *ChangePinRequest, opts ...http.CallOption) (*ChangePinReply, error) {
	var out ChangePinReply
	pattern := "/api/app_server/change_pin"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserChangePin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.SendBody, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) CheckCard(ctx context.Context, in *CheckCardRequest, opts ...http.CallOption) (*CheckCardReply, error) {
	var out CheckCardReply
	pattern := "/api/app_server/check_card"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserCheckCard))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.SendBody, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) CodeList(ctx context.Context, in *CodeListRequest, opts ...http.CallOption) (*CodeListReply, error) {
	var out CodeListReply
	pattern := "/api/app_server/code_list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserCodeList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) CreateNonce(ctx context.Context, in *CreateNonceRequest, opts ...http.CallOption) (*CreateNonceReply, error) {
	var out CreateNonceReply
	pattern := "/api/app_server/create_nonce"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserCreateNonce))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.SendBody, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) EthAuthorize(ctx context.Context, in *EthAuthorizeRequest, opts ...http.CallOption) (*EthAuthorizeReply, error) {
	var out EthAuthorizeReply
	pattern := "/api/app_server/eth_authorize"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserEthAuthorize))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.SendBody, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) GetUser(ctx context.Context, in *GetUserRequest, opts ...http.CallOption) (*GetUserReply, error) {
	var out GetUserReply
	pattern := "/api/app_server/user"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserGetUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) LookCard(ctx context.Context, in *LookCardRequest, opts ...http.CallOption) (*LookCardReply, error) {
	var out LookCardReply
	pattern := "/api/app_server/look_card"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserLookCard))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.SendBody, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) LookCardNew(ctx context.Context, in *LookCardRequest, opts ...http.CallOption) (*LookCardReply, error) {
	var out LookCardReply
	pattern := "/api/app_server/look_card_new"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserLookCardNew))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.SendBody, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) LookCardNewTwo(ctx context.Context, in *LookCardRequest, opts ...http.CallOption) (*LookCardReply, error) {
	var out LookCardReply
	pattern := "/api/app_server/change_card"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserLookCardNewTwo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.SendBody, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) OpenCard(ctx context.Context, in *OpenCardRequest, opts ...http.CallOption) (*OpenCardReply, error) {
	var out OpenCardReply
	pattern := "/api/app_server/open_card"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserOpenCard))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.SendBody, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) OpenCardTwo(ctx context.Context, in *OpenCardRequest, opts ...http.CallOption) (*OpenCardReply, error) {
	var out OpenCardReply
	pattern := "/api/app_server/open_card_two"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserOpenCardTwo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.SendBody, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) OrderList(ctx context.Context, in *OrderListRequest, opts ...http.CallOption) (*OrderListReply, error) {
	var out OrderListReply
	pattern := "/api/app_server/order_list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserOrderList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) OrderListTwo(ctx context.Context, in *OrderListTwoRequest, opts ...http.CallOption) (*OrderListTwoReply, error) {
	var out OrderListTwoReply
	pattern := "/api/app_server/order_list_new"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserOrderListTwo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) RecordList(ctx context.Context, in *RecordListRequest, opts ...http.CallOption) (*RecordListReply, error) {
	var out RecordListReply
	pattern := "/api/app_server/record_list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserRecordList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) RewardList(ctx context.Context, in *RewardListRequest, opts ...http.CallOption) (*RewardListReply, error) {
	var out RewardListReply
	pattern := "/api/app_server/reward_list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserRewardList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) SetVip(ctx context.Context, in *SetVipRequest, opts ...http.CallOption) (*SetVipReply, error) {
	var out SetVipReply
	pattern := "/api/app_server/set_vip"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserSetVip))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.SendBody, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) UserRecommend(ctx context.Context, in *RecommendListRequest, opts ...http.CallOption) (*RecommendListReply, error) {
	var out RecommendListReply
	pattern := "/api/app_server/recommend_list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserUserRecommend))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserHTTPClientImpl) Withdraw(ctx context.Context, in *WithdrawRequest, opts ...http.CallOption) (*WithdrawReply, error) {
	var out WithdrawReply
	pattern := "/api/app_server/withdraw"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserWithdraw))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.SendBody, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
